language: node_js

node_js:
  - 8
  - 10

matrix:
  fast_finish: true

notifications:
  email: false
  slack:
    secure: rbUUN+ID+aOWbUNcvo6dDvhV0Ka1pvFi9Cz8cB9SQcrtGDE+9Swd6DVPQmDAB5U4r1s1f9AUz5isDnC7b2K72r3vOlutlLBQ1Q2lP/6qzidrFLyNJvkcMSUziNX+Q8snvzF+lojq7jno0YhGfR4CLpoj5oJ0O4xc5gEbpfIfILcbs4svFcg9y5KqbDudRCMdWPz4YOfbZ2eVo2S4YNmooxNAotkbA6kaazArG6ClGwUE7QFoVdpLI6eKlGIn0m8pzwkzHArkauwkKak2prseWy4QKA2hVwMcuATX1slG9dtZ7NEFCUgXMS9zrz3GhcqwCBjOTKKX8FjM+gFkXM24E9QgEdRoNp8uAQTmssASGEBoM6foEq+x2nTkADwDCywz4ImTEpUqGv13oQRvLbLA0P57I5SREz2ONbBTA6mwAAeV0dmZiy1c5OmyzJ6nDw0qZBbPIWIvYoTwuIRcThCiltbhZ0+Bg389gfmJfJIY3hDo8KuCTPfbdlZznZh2I22sHOAj+PnktK8PY4az+MrAOMGMtd2QQO3i8WSrW3jfsYbAOLVG4DvWdjfL+noqrU5QHEIQ7wy93s0JICERzLc+ZJJ4rRgz3iM899aIMLmvu0RvGIVRfqtDYeLzpYqiQwFND+83HuswQKfBlLRhqOZSoUqBXgxJbHSy59VxrBhXfSc=

cache:
  directories:
    - $HOME/.npm
